# Generated by Django 5.0 on 2026-07-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="repeat_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Nach wievielen Tagen sich das Event wiederholt",
                null=True,
                verbose_name="Tage",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="repeat_ends",
            field=models.DateField(
                blank=True,
                help_text="Format: dd.mm.YYYY",
                null=True,
                verbose_name="Wiederholungsende",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="repeats",
            field=models.BooleanField(
                default=False,
                help_text="Ob sich das Event wiederholt",
                verbose_name="Wiederholend",
            ),
        ),
    ]
