# Generated by Django 5.0 on 2026-06-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_merge_20201206_2211"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentdownload",
            new_name="documents_d_documen_d84a7d_idx",
            old_fields=("document", "timestamp"),
        ),
    ]
